[project]
name = "clive-userflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Justin Rainier Go", email = "jrgo.dev@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
clive-userflow = "clive_userflow:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
